package chen.dao;

import chen.dto.CategoryDto;
import chen.entity.Category;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public interface CategoryDtoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_category
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer categoryid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_category
     *
     * @mbggenerated
     */
    int insert(CategoryDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_category
     *
     * @mbggenerated
     */
    int insertSelective(CategoryDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_category
     *
     * @mbggenerated
     */
    CategoryDto selectByPrimaryKey(Integer categoryid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_category
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CategoryDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_category
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CategoryDto record);

    List<Category> getCategories();
}