package chen.dao;

import chen.dto.LinkDto;
import chen.entity.Link;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public interface LinkDtoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_link
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer linkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_link
     *
     * @mbggenerated
     */
    int insert(LinkDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_link
     *
     * @mbggenerated
     */
    int insertSelective(LinkDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_link
     *
     * @mbggenerated
     */
    LinkDto selectByPrimaryKey(Integer linkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_link
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(LinkDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_link
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LinkDto record);

    List<Link> getLinks();
}