package chen.dao;

import chen.dto.MessageDto;
import org.springframework.stereotype.Component;

@Component
public interface MessageDtoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_message
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer messageid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_message
     *
     * @mbggenerated
     */
    int insert(MessageDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_message
     *
     * @mbggenerated
     */
    int insertSelective(MessageDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_message
     *
     * @mbggenerated
     */
    MessageDto selectByPrimaryKey(Integer messageid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_message
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MessageDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_message
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MessageDto record);
}